import Foundation

public enum AppTextKey: String, CaseIterable, Sendable {
    case menuShowPet
    case menuSettings
    case menuRequestAccessibility
    case menuOpenAccessibility
    case menuInstallHook
    case menuUninstallHook
    case menuQuit
    case settingsWindowTitle
    case settingsAbout
    case settingsAppearance
    case settingsLanguage
    case settingsCommands
    case settingsPet
    case settingsPersonality
    case settingsModel
    case languageTitle
    case languageRestartNote
    case saveConfig
    case saved
    case petUnselected
    case petSelectPrompt
    case petCurrentFolder
    case petNoFolder
    case petChooseFolder
    case petImportFolder
    case commandPanelTitle
    case commandPanelAdd
    case commandPanelPin
    case commandPanelUnpin
    case quotaTitle
    case quotaRefresh
    case quotaReading
    case quotaPending
    case quotaNoData
    case quotaSynced
    case quotaLoginRequired
    case quotaNotLoggedIn
    case quotaError
    case quotaReadingDetail
    case quotaHoverDetail
    case quotaEmptyDetail
    case quotaReset
    case actionIdle
    case actionRun
    case actionMove
    case actionHappy
    case actionAlert
    case actionError
    case actionSleep
    case actionThink
    case actionCelebrate
    case contextMenuRandomPet
    case contextMenuSettings
    case contextMenuQuit
    case aboutVersion
    case aboutTitle
    case aboutDescription
    case aboutDeveloper
    case aboutDeveloperName
    case aboutSocialMedia
    case skinGlass
    case skinDark
    case skinPixel
    case personalityHappy
    case personalityCodingPartner
    case personalityGentleCoach
    case personalityFocused
    case personalityAngry
    case personalityLazy
    case personalityEnergetic
    case personalityWise
    case personalitySarcastic
    case personalityCustom
    case menuEdit
    case menuClose
    case menuUndo
    case menuRedo
    case menuCut
    case menuCopy
    case menuPaste
    case menuSelectAll
    case alertOK
    case hookInstalledTitle
    case hookInstalledMessage
    case hookInstallFailedTitle
    case hookUninstalledTitle
    case hookUninstalledMessage
    case hookUninstallFailedTitle
    case petFolderPanelPrompt
    case petFolderPanelMessage
    case menuResetAccessibility
    case accessibilityResetTitle
    case accessibilityResetMessage
    case accessibilityResetFailedTitle
    case accessibilityNeedsAuthTitle
    case accessibilityNeedsAuthMessage
    case modelPetChatTitle
    case modelRefresh
    case modelProviderSource
    case modelRedetect
    case modelSwitchToOnline
    case modelTagLocal
    case modelTagDownloaded
    case modelButtonDownload
    case modelButtonRetry
    case modelButtonDelete
    case modelDeleteConfirmTitle
    case modelDeleteConfirmMessage
    case modelStartOllama
    case modelInstallOllama
    case modelStarting
    case modelDownloadRecommended
    case modelDownloadingShort
    case modelUseLocal
    case modelRetryDownload
    case modelOpenInstallPage
    case modelSetupTitleNotInstalled
    case modelSetupTitleStarting
    case modelSetupTitleRunningNoModel
    case modelSetupTitleDownloadingModel
    case modelSetupTitleReady
    case modelSetupTitleError
    case modelSetupMsgNotInstalled
    case modelSetupMsgStarting
    case modelSetupMsgRunningNoModelPrefix
    case modelSetupMsgRunningNoModelSuffix
    case modelSetupMsgDownloadingModel
    case modelSetupMsgReady
    case modelSetupMsgErrorFallback
    case modelBadgeNotDetected
    case modelBadgeStarting
    case modelBadgePending
    case modelBadgeDownloading
    case modelBadgeReady
    case modelBadgeError
    case modelOnlineApiProvider
    case modelReadingShort
    case modelReadModels
    case modelTestingShort
    case modelTestConnection
    case modelLabel
    case modelSelectAfterRead
    case modelStateReadingList
    case modelStateReadDonePrefix
    case modelStateSendingTest
    case modelDownloadingProgressPrefix
    case modelSaveButton
    case modelProviderLocal
    case modelProviderOnline
    case modelOnlineProviderCustom
    case ollamaDescQwenSmall
    case ollamaDescQwenRecommended
    case ollamaDescPhi35
    case ollamaDescGemma1b
    case commandsAdd
    case commandsPinnedSection
    case commandsAllSection
    case commandsDragSort
    case commandsUnpin
    case commandsPin
    case commandsDelete
    case commandsAutoSave
    case addCommandTitle
    case addCommandDescriptionLabel
    case addCommandDescriptionPlaceholder
    case cmdSummaryClaude
    case cmdSummaryClaudeAuto
    case cmdSummaryClaudeDanger
    case cmdSummaryCompact
    case cmdSummaryInit
    case cmdSummaryClear
    case cmdSummaryMemory
    case cmdSummaryModel
    case cmdSummaryHelp
    case cmdSummaryReview
    case cmdSummaryStatus
    case cmdSummaryDiff
    case cmdSummaryCost
    case cmdSummaryLogin
    case cmdSummaryConfig
    case cmdSummaryMcp
    case cmdSummaryDoctor
    case cmdSummaryTerminalSetup
    case commandMoveUp
    case commandMoveDown
    case addCommandNameLabel
    case addCommandNamePlaceholder
    case addCommandContentLabel
    case addCommandCancel
    case addCommandConfirm
    case personalityPetName
    case personalityPetNamePlaceholder
    case personalityOwnerName
    case personalityOwnerNamePlaceholder
    case personalityPresetSection
    case personalityCustomPrompt
    case personalityPromptEditable
    case personalityConstraints
    case personalityConstraintPlaceholder
    case personalitySaveButton
    case personalitySaved
    case personalitySaveFailed
    case skinPickerTitle
    case skinGlassDesc
    case skinDarkDesc
    case skinPixelDesc
    case chatInputPlaceholder
    case petImportedSection
    case petButtonChoose
    case petButtonChosen
    case petTooltipDelete
    case petTooltipKeepOne
    case tooltipChooseFolderAndCd
    case tooltipChatWithPet
    case tooltipSwitchSkin
    case tooltipStopPomodoro
    case tooltipStartBreak5
    case tooltipCloseStatus
    case pomodoroStart25
    case pomodoroPausedRemain
    case pomodoroWorkingRemain
    case pomodoroBreakPausedRemain
    case pomodoroBreakingRemain
    case statusCommandsTab
    case statusAllowHint
    case statusDenyAuth
    case petBuiltinTermicatName
    case petBuiltinTermicatDesc
    case petBuiltinJituiName
    case petBuiltinJituiDesc
    case petBuiltinWizardClaudeName
    case petBuiltinWizardClaudeDesc
    case petBuiltinPixelJituiName
    case petBuiltinPixelJituiDesc
    case petFromPetdexCommunity
}

public struct AppLocalizer: Sendable, Equatable {
    public let language: AppLanguage

    public init(language: AppLanguage = AppLanguageStore().load()) {
        self.language = language
    }

    public func text(_ key: AppTextKey) -> String {
        Self.table[language]?[key] ?? Self.table[.simplifiedChinese]?[key] ?? key.rawValue
    }

    public subscript(_ key: AppTextKey) -> String {
        text(key)
    }

    private static let table: [AppLanguage: [AppTextKey: String]] = [
        .simplifiedChinese: [
            .menuShowPet: "显示宠物",
            .menuSettings: "设置...",
            .menuRequestAccessibility: "请求辅助功能授权",
            .menuOpenAccessibility: "打开辅助功能设置",
            .menuInstallHook: "安装 Claude Code Hook",
            .menuUninstallHook: "卸载 Claude Code Hook",
            .menuQuit: "退出",
            .settingsWindowTitle: "TermiPet 设置",
            .settingsAbout: "关于",
            .settingsAppearance: "皮肤",
            .settingsLanguage: "语言",
            .settingsCommands: "快捷指令",
            .settingsPet: "宠物",
            .settingsPersonality: "性格",
            .settingsModel: "模型",
            .languageTitle: "选择界面语言",
            .languageRestartNote: "注意：语言切换需要重启应用生效",
            .saveConfig: "保存配置",
            .saved: "已保存",
            .petUnselected: "未选择宠物",
            .petSelectPrompt: "请选择一个包含 pet.json 和 spritesheet 的宠物文件夹。",
            .petCurrentFolder: "当前文件夹",
            .petNoFolder: "无",
            .petChooseFolder: "选择宠物文件夹",
            .petImportFolder: "导入宠物文件夹",
            .commandPanelTitle: "快捷指令",
            .commandPanelAdd: "添加自定义快捷指令",
            .commandPanelPin: "固定快捷指令面板",
            .commandPanelUnpin: "取消固定快捷指令面板",
            .quotaTitle: "AI 用量",
            .quotaRefresh: "刷新用量",
            .quotaReading: "读取中",
            .quotaPending: "待读取",
            .quotaNoData: "无数据",
            .quotaSynced: "已同步",
            .quotaLoginRequired: "需登录",
            .quotaNotLoggedIn: "未登录",
            .quotaError: "错误",
            .quotaReadingDetail: "正在读取套餐用量...",
            .quotaHoverDetail: "悬停后读取套餐用量",
            .quotaEmptyDetail: "没有可显示的用量数据",
            .quotaReset: "已重置",
            .actionIdle: "待机",
            .actionRun: "运行",
            .actionMove: "移动",
            .actionHappy: "开心",
            .actionAlert: "提醒",
            .actionError: "错误",
            .actionSleep: "睡觉",
            .actionThink: "思考",
            .actionCelebrate: "庆祝",
            .contextMenuRandomPet: "随机宠物",
            .contextMenuSettings: "设置...",
            .contextMenuQuit: "关闭宠物",
            .aboutVersion: "版本",
            .aboutTitle: "桌面浮动终端宠物助手",
            .aboutDescription: "TermiPet 是一款智能桌面宠物助手，为开发者提供全方位的编程辅助功能。\n\n核心功能：\n• 快捷指令面板 - 一键执行常用终端命令\n• 终端实时预览 - 自动识别并显示终端输出状态\n• Claude Code 集成 - 实时监控 AI 编程助手工作状态\n• 番茄钟计时器 - 帮助保持专注和高效工作节奏\n• AI 聊天对话 - 与宠物智能交互，获取编程建议\n• 多皮肤主题 - 玻璃、暗黑、像素风格随心切换\n• 自定义宠物 - 支持导入个性化宠物资源包\n• 多语言支持 - 简中、繁中、英语、日语、韩语\n• AI 用量监控 - 实时显示 Claude/Copilot/ChatGPT 配额\n\n让编程更高效、更有趣！",
            .aboutDeveloper: "开发者",
            .aboutDeveloperName: "由 bleetchen 开发",
            .aboutSocialMedia: "社交媒体",
            .skinGlass: "玻璃",
            .skinDark: "暗黑",
            .skinPixel: "像素",
            .personalityHappy: "开心",
            .personalityCodingPartner: "编程搭子",
            .personalityGentleCoach: "温柔教练",
            .personalityFocused: "专注提醒",
            .personalityAngry: "愤怒",
            .personalityLazy: "慵懒",
            .personalityEnergetic: "元气",
            .personalityWise: "睿智",
            .personalitySarcastic: "毒舌",
            .personalityCustom: "自定义",
            .menuEdit: "编辑",
            .menuClose: "关闭窗口",
            .menuUndo: "撤销",
            .menuRedo: "重做",
            .menuCut: "剪切",
            .menuCopy: "复制",
            .menuPaste: "粘贴",
            .menuSelectAll: "全选",
            .alertOK: "好",
            .hookInstalledTitle: "已安装",
            .hookInstalledMessage: "Claude Code Hook 已写入。请重启正在运行的 claude 进程让 hook 生效。",
            .hookInstallFailedTitle: "安装失败",
            .hookUninstalledTitle: "已卸载",
            .hookUninstalledMessage: "Claude Code Hook 已从 ~/.claude/settings.json 移除。",
            .hookUninstallFailedTitle: "卸载失败",
            .petFolderPanelPrompt: "导入",
            .petFolderPanelMessage: "选择包含 pet.json 和 spritesheet 的宠物文件夹",
            .menuResetAccessibility: "重置辅助功能授权",
            .accessibilityResetTitle: "已重置辅助功能授权",
            .accessibilityResetMessage: "TCC 关于 TermiPet 的旧记录已清除。请退出 TermiPet 后重新打开，下次点击快捷指令时会弹一次干净的授权对话框，选「允许」即可。",
            .accessibilityResetFailedTitle: "重置失败",
            .accessibilityNeedsAuthTitle: "需要辅助功能授权",
            .accessibilityNeedsAuthMessage: "内容已复制到剪贴板，到终端按 Cmd+V 即可粘贴。\n\n如果系统设置里 TermiPet 已经打勾但仍提示，是因为磁盘上有多份同名 .app 拥有不同的代码签名 hash。请：\n1. 关闭 TermiPet\n2. 系统设置 → 隐私与安全性 → 辅助功能，找到 TermiPet 点 − 号删除\n3. 删除多余的 TermiPet.app 副本，只保留当前这份\n4. 重新打开 TermiPet，再点快捷指令时同意授权\n\n你也可以使用菜单栏「重置辅助功能授权」一键清理。",
            .modelPetChatTitle: "宠物对话模型",
            .modelRefresh: "刷新",
            .modelProviderSource: "模型来源",
            .modelRedetect: "重新检测",
            .modelSwitchToOnline: "改用线上 API",
            .modelTagLocal: "本地模型",
            .modelTagDownloaded: "已下载",
            .modelButtonDownload: "下载",
            .modelButtonRetry: "重试",
            .modelButtonDelete: "删除模型",
            .modelDeleteConfirmTitle: "删除 %@？",
            .modelDeleteConfirmMessage: "这会从 Ollama 中删除 %@。删除后可以重新下载，用来修复模型损坏或无法对话的问题。",
            .modelStartOllama: "启动 Ollama",
            .modelInstallOllama: "安装 Ollama",
            .modelStarting: "启动中",
            .modelDownloadRecommended: "下载推荐模型",
            .modelDownloadingShort: "下载中",
            .modelUseLocal: "使用本地模型",
            .modelRetryDownload: "重试下载",
            .modelOpenInstallPage: "打开安装页",
            .modelSetupTitleNotInstalled: "先启动本地模型服务",
            .modelSetupTitleStarting: "正在启动 Ollama",
            .modelSetupTitleRunningNoModel: "下载推荐模型",
            .modelSetupTitleDownloadingModel: "模型正在下载",
            .modelSetupTitleReady: "本地模型已就绪",
            .modelSetupTitleError: "本地模型还没准备好",
            .modelSetupMsgNotInstalled: "TermiPet 没有检测到 Ollama。可以先尝试启动，没安装的话再打开官方安装页。",
            .modelSetupMsgStarting: "正在打开 Ollama，稍等几秒后会自动重新检测。",
            .modelSetupMsgRunningNoModelPrefix: "Ollama 已运行。下载 ",
            .modelSetupMsgRunningNoModelSuffix: " 后，宠物就可以用本地模型聊天。",
            .modelSetupMsgDownloadingModel: "请保持网络连接，下载中断后可以重试，不会影响已有设置。",
            .modelSetupMsgReady: "已有本地模型可用，TermiPet 会优先使用已选中的本地模型。",
            .modelSetupMsgErrorFallback: "请确认 Ollama 正在运行，或者重新打开官方安装页。",
            .modelBadgeNotDetected: "未检测到",
            .modelBadgeStarting: "启动中",
            .modelBadgePending: "待下载",
            .modelBadgeDownloading: "下载中",
            .modelBadgeReady: "已就绪",
            .modelBadgeError: "需处理",
            .modelOnlineApiProvider: "API 提供方",
            .modelReadingShort: "读取中...",
            .modelReadModels: "读取模型",
            .modelTestingShort: "测试中...",
            .modelTestConnection: "测试连接",
            .modelLabel: "模型",
            .modelSelectAfterRead: "点击\u{201C}读取模型\u{201D}后可选择",
            .modelStateReadingList: "正在读取模型列表",
            .modelStateReadDonePrefix: "已读取 ",
            .modelStateSendingTest: "正在发送测试消息",
            .modelDownloadingProgressPrefix: "正在下载 ",
            .modelSaveButton: "保存配置",
            .modelProviderLocal: "本地模型",
            .modelProviderOnline: "线上 API",
            .modelOnlineProviderCustom: "自定义 API",
            .ollamaDescQwenSmall: "极轻量，适合低配，中文优秀",
            .ollamaDescQwenRecommended: "推荐，中文最优，速度快",
            .ollamaDescPhi35: "微软出品，小体积高质量",
            .ollamaDescGemma1b: "Google 出品，均衡轻量",
            .commandsAdd: "添加",
            .commandsPinnedSection: "置顶指令",
            .commandsAllSection: "全部指令",
            .commandsDragSort: "拖动排序",
            .commandsUnpin: "取消置顶",
            .commandsPin: "置顶",
            .commandsDelete: "删除",
            .commandsAutoSave: "自动保存",
            .addCommandTitle: "添加快捷指令",
            .addCommandDescriptionLabel: "描述 / 备注",
            .addCommandDescriptionPlaceholder: "解释这个指令是做什么的",
            .cmdSummaryClaude: "启动 Claude Code 交互会话",
            .cmdSummaryClaudeAuto: "开启自动模式，减少手动确认",
            .cmdSummaryClaudeDanger: "跳过权限提示，适合受控环境",
            .cmdSummaryCompact: "压缩上下文，保留当前任务重点",
            .cmdSummaryInit: "生成或更新项目说明文件",
            .cmdSummaryClear: "清空当前对话上下文",
            .cmdSummaryMemory: "查看或管理 Claude 记忆",
            .cmdSummaryModel: "切换当前使用的模型",
            .cmdSummaryHelp: "查看 Claude Code 帮助",
            .cmdSummaryReview: "请求代码审查建议",
            .cmdSummaryStatus: "查看当前会话和工具状态",
            .cmdSummaryDiff: "查看本次修改差异",
            .cmdSummaryCost: "查看当前会话消耗",
            .cmdSummaryLogin: "登录或切换账号",
            .cmdSummaryConfig: "打开配置相关选项",
            .cmdSummaryMcp: "管理 MCP 服务器连接",
            .cmdSummaryDoctor: "检查本地环境问题",
            .cmdSummaryTerminalSetup: "配置终端集成能力",
            .commandMoveUp: "上移",
            .commandMoveDown: "下移",
            .addCommandNameLabel: "名称",
            .addCommandNamePlaceholder: "例如：打开项目",
            .addCommandContentLabel: "输入内容",
            .addCommandCancel: "取消",
            .addCommandConfirm: "确认",
            .personalityPetName: "宠物名称",
            .personalityPetNamePlaceholder: "小宠",
            .personalityOwnerName: "主人名字",
            .personalityOwnerNamePlaceholder: "主人",
            .personalityPresetSection: "性格预设",
            .personalityCustomPrompt: "自定义 Prompt",
            .personalityPromptEditable: "Prompt（可继续编辑）",
            .personalityConstraints: "约束条件",
            .personalityConstraintPlaceholder: "例如：只说中文、不说脏话...",
            .personalitySaveButton: "保存配置",
            .personalitySaved: "已保存",
            .personalitySaveFailed: "保存失败",
            .skinPickerTitle: "选择皮肤",
            .skinGlassDesc: "毛玻璃、柔和边缘",
            .skinDarkDesc: "低亮度夜间面板",
            .skinPixelDesc: "硬边框、像素感",
            .chatInputPlaceholder: "说点什么…",
            .petImportedSection: "已导入宠物",
            .petButtonChoose: "选择",
            .petButtonChosen: "已选择",
            .petTooltipDelete: "删除宠物",
            .petTooltipKeepOne: "至少需要保留一个宠物",
            .tooltipChooseFolderAndCd: "选择文件夹并输入 cd",
            .tooltipChatWithPet: "与宠物聊天",
            .tooltipSwitchSkin: "切换皮肤",
            .tooltipStopPomodoro: "停止番茄钟",
            .tooltipStartBreak5: "开始休息 (5 分钟)",
            .tooltipCloseStatus: "关闭状态",
            .pomodoroStart25: "开始番茄钟 (25 分钟)",
            .pomodoroPausedRemain: "已暂停 · 剩余 %@ · 点击继续",
            .pomodoroWorkingRemain: "工作中 · 剩余 %@ · 点击暂停",
            .pomodoroBreakPausedRemain: "休息已暂停 · 剩余 %@ · 点击继续",
            .pomodoroBreakingRemain: "休息中 · 剩余 %@ · 点击暂停",
            .statusCommandsTab: "命令",
            .statusAllowHint: "允许 · %@",
            .statusDenyAuth: "拒绝授权",
            .petBuiltinTermicatName: "termicat",
            .petBuiltinTermicatDesc: "一只蜷在迷你终端旁边的彩虹像素小猫。",
            .petBuiltinJituiName: "鸡腿",
            .petBuiltinJituiDesc: "开发者主人的猫咪。",
            .petBuiltinWizardClaudeName: "巫师克劳德",
            .petBuiltinWizardClaudeDesc: "戴着深蓝魔法帽和披风的橙色巫师宠物，闪着小小的金色魔法。",
            .petBuiltinPixelJituiName: "像素鸡腿",
            .petBuiltinPixelJituiDesc: "开发者的猫咪。",
            .petFromPetdexCommunity: "来自 Petdex 社区",
        ],
        .traditionalChinese: [
            .menuShowPet: "顯示寵物",
            .menuSettings: "設定...",
            .menuRequestAccessibility: "請求輔助使用授權",
            .menuOpenAccessibility: "打開輔助使用設定",
            .menuInstallHook: "安裝 Claude Code Hook",
            .menuUninstallHook: "解除安裝 Claude Code Hook",
            .menuQuit: "退出",
            .settingsWindowTitle: "TermiPet 設定",
            .settingsAbout: "關於",
            .settingsAppearance: "外觀",
            .settingsLanguage: "語言",
            .settingsCommands: "快捷指令",
            .settingsPet: "寵物",
            .settingsPersonality: "性格",
            .settingsModel: "模型",
            .languageTitle: "選擇介面語言",
            .languageRestartNote: "注意：語言切換需要重新啟動應用程式才會生效",
            .saveConfig: "儲存設定",
            .saved: "已儲存",
            .petUnselected: "尚未選擇寵物",
            .petSelectPrompt: "請選擇包含 pet.json 和 spritesheet 的寵物資料夾。",
            .petCurrentFolder: "目前資料夾",
            .petNoFolder: "無",
            .petChooseFolder: "選擇寵物資料夾",
            .petImportFolder: "匯入寵物資料夾",
            .commandPanelTitle: "快捷指令",
            .commandPanelAdd: "新增自訂快捷指令",
            .commandPanelPin: "固定快捷指令面板",
            .commandPanelUnpin: "取消固定快捷指令面板",
            .quotaTitle: "AI 用量",
            .quotaRefresh: "重新整理用量",
            .quotaReading: "讀取中",
            .quotaPending: "待讀取",
            .quotaNoData: "無資料",
            .quotaSynced: "已同步",
            .quotaLoginRequired: "需登入",
            .quotaNotLoggedIn: "未登入",
            .quotaError: "錯誤",
            .quotaReadingDetail: "正在讀取套餐用量...",
            .quotaHoverDetail: "懸停後讀取套餐用量",
            .quotaEmptyDetail: "沒有可顯示的用量資料",
            .quotaReset: "已重置",
            .actionIdle: "待機",
            .actionRun: "運行",
            .actionMove: "移動",
            .actionHappy: "開心",
            .actionAlert: "提醒",
            .actionError: "錯誤",
            .actionSleep: "睡覺",
            .actionThink: "思考",
            .actionCelebrate: "慶祝",
            .contextMenuRandomPet: "隨機寵物",
            .contextMenuSettings: "設定...",
            .contextMenuQuit: "關閉寵物",
            .aboutVersion: "版本",
            .aboutTitle: "桌面浮動終端寵物助手",
            .aboutDescription: "TermiPet 是一款智慧桌面寵物助手，為開發者提供全方位的程式設計輔助功能。\n\n核心功能：\n• 快捷指令面板 - 一鍵執行常用終端指令\n• 終端即時預覽 - 自動識別並顯示終端輸出狀態\n• Claude Code 整合 - 即時監控 AI 程式設計助手工作狀態\n• 番茄鐘計時器 - 幫助保持專注和高效工作節奏\n• AI 聊天對話 - 與寵物智慧互動，獲取程式設計建議\n• 多皮膚主題 - 玻璃、暗黑、像素風格隨心切換\n• 自訂寵物 - 支援匯入個人化寵物資源包\n• 多語言支援 - 簡中、繁中、英語、日語、韓語\n• AI 用量監控 - 即時顯示 Claude/Copilot/ChatGPT 配額\n\n讓程式設計更高效、更有趣！",
            .aboutDeveloper: "開發者",
            .aboutDeveloperName: "由 bleetchen 開發",
            .aboutSocialMedia: "社交媒體",
            .skinGlass: "玻璃",
            .skinDark: "暗黑",
            .skinPixel: "像素",
            .personalityHappy: "開心",
            .personalityCodingPartner: "程式設計搭子",
            .personalityGentleCoach: "溫柔教練",
            .personalityFocused: "專注提醒",
            .personalityAngry: "憤怒",
            .personalityLazy: "慵懶",
            .personalityEnergetic: "元氣",
            .personalityWise: "睿智",
            .personalitySarcastic: "毒舌",
            .personalityCustom: "自訂",
            .menuEdit: "編輯",
            .menuClose: "關閉視窗",
            .menuUndo: "復原",
            .menuRedo: "重做",
            .menuCut: "剪下",
            .menuCopy: "拷貝",
            .menuPaste: "貼上",
            .menuSelectAll: "全選",
            .alertOK: "好",
            .hookInstalledTitle: "已安裝",
            .hookInstalledMessage: "Claude Code Hook 已寫入。請重新啟動正在執行的 claude 程序讓 hook 生效。",
            .hookInstallFailedTitle: "安裝失敗",
            .hookUninstalledTitle: "已解除安裝",
            .hookUninstalledMessage: "Claude Code Hook 已從 ~/.claude/settings.json 移除。",
            .hookUninstallFailedTitle: "解除安裝失敗",
            .petFolderPanelPrompt: "匯入",
            .petFolderPanelMessage: "選擇包含 pet.json 和 spritesheet 的寵物資料夾",
            .menuResetAccessibility: "重置輔助使用授權",
            .accessibilityResetTitle: "已重置輔助使用授權",
            .accessibilityResetMessage: "TCC 中 TermiPet 的舊紀錄已清除。請結束 TermiPet 後重新開啟，下次點擊快捷指令時會出現一次乾淨的授權對話框，選「允許」即可。",
            .accessibilityResetFailedTitle: "重置失敗",
            .accessibilityNeedsAuthTitle: "需要輔助使用授權",
            .accessibilityNeedsAuthMessage: "內容已複製到剪貼簿，到終端機按 Cmd+V 即可貼上。\n\n若系統設定裡 TermiPet 已勾選但仍提示，通常是因為磁碟上有多份同名 .app 擁有不同的程式碼簽章 hash。請：\n1. 關閉 TermiPet\n2. 系統設定 → 隱私權與安全性 → 輔助使用，找到 TermiPet 按 − 號移除\n3. 刪除多餘的 TermiPet.app 副本，只保留目前這份\n4. 重新開啟 TermiPet，再點快捷指令時同意授權\n\n你也可以使用選單列「重置輔助使用授權」一鍵清理。",
            .modelPetChatTitle: "寵物對話模型",
            .modelRefresh: "重新整理",
            .modelProviderSource: "模型來源",
            .modelRedetect: "重新偵測",
            .modelSwitchToOnline: "改用線上 API",
            .modelTagLocal: "本地模型",
            .modelTagDownloaded: "已下載",
            .modelButtonDownload: "下載",
            .modelButtonRetry: "重試",
            .modelButtonDelete: "刪除模型",
            .modelDeleteConfirmTitle: "刪除 %@？",
            .modelDeleteConfirmMessage: "這會從 Ollama 中刪除 %@。刪除後可以重新下載，用來修復模型損壞或無法對話的問題。",
            .modelStartOllama: "啟動 Ollama",
            .modelInstallOllama: "安裝 Ollama",
            .modelStarting: "啟動中",
            .modelDownloadRecommended: "下載推薦模型",
            .modelDownloadingShort: "下載中",
            .modelUseLocal: "使用本地模型",
            .modelRetryDownload: "重試下載",
            .modelOpenInstallPage: "開啟安裝頁",
            .modelSetupTitleNotInstalled: "先啟動本地模型服務",
            .modelSetupTitleStarting: "正在啟動 Ollama",
            .modelSetupTitleRunningNoModel: "下載推薦模型",
            .modelSetupTitleDownloadingModel: "模型正在下載",
            .modelSetupTitleReady: "本地模型已就緒",
            .modelSetupTitleError: "本地模型尚未準備好",
            .modelSetupMsgNotInstalled: "TermiPet 沒有偵測到 Ollama。可以先嘗試啟動，沒安裝的話再開啟官方安裝頁。",
            .modelSetupMsgStarting: "正在開啟 Ollama，稍等幾秒後會自動重新偵測。",
            .modelSetupMsgRunningNoModelPrefix: "Ollama 已執行。下載 ",
            .modelSetupMsgRunningNoModelSuffix: " 後，寵物就可以用本地模型聊天。",
            .modelSetupMsgDownloadingModel: "請保持網路連線，下載中斷後可以重試，不會影響既有設定。",
            .modelSetupMsgReady: "已有本地模型可用，TermiPet 會優先使用已選取的本地模型。",
            .modelSetupMsgErrorFallback: "請確認 Ollama 正在執行，或重新開啟官方安裝頁。",
            .modelBadgeNotDetected: "未偵測到",
            .modelBadgeStarting: "啟動中",
            .modelBadgePending: "待下載",
            .modelBadgeDownloading: "下載中",
            .modelBadgeReady: "已就緒",
            .modelBadgeError: "需處理",
            .modelOnlineApiProvider: "API 提供方",
            .modelReadingShort: "讀取中...",
            .modelReadModels: "讀取模型",
            .modelTestingShort: "測試中...",
            .modelTestConnection: "測試連線",
            .modelLabel: "模型",
            .modelSelectAfterRead: "點擊\u{201C}讀取模型\u{201D}後可選擇",
            .modelStateReadingList: "正在讀取模型列表",
            .modelStateReadDonePrefix: "已讀取 ",
            .modelStateSendingTest: "正在傳送測試訊息",
            .modelDownloadingProgressPrefix: "正在下載 ",
            .modelSaveButton: "儲存設定",
            .modelProviderLocal: "本地模型",
            .modelProviderOnline: "線上 API",
            .modelOnlineProviderCustom: "自訂 API",
            .ollamaDescQwenSmall: "極輕量，適合低配，中文優秀",
            .ollamaDescQwenRecommended: "推薦，中文最優，速度快",
            .ollamaDescPhi35: "微軟出品，小體積高品質",
            .ollamaDescGemma1b: "Google 出品，均衡輕量",
            .commandsAdd: "新增",
            .commandsPinnedSection: "置頂指令",
            .commandsAllSection: "全部指令",
            .commandsDragSort: "拖曳排序",
            .commandsUnpin: "取消置頂",
            .commandsPin: "置頂",
            .commandsDelete: "刪除",
            .commandsAutoSave: "自動儲存",
            .addCommandTitle: "新增快捷指令",
            .addCommandDescriptionLabel: "描述 / 備註",
            .addCommandDescriptionPlaceholder: "說明這個指令的作用",
            .cmdSummaryClaude: "啟動 Claude Code 互動對話",
            .cmdSummaryClaudeAuto: "開啟自動模式，減少手動確認",
            .cmdSummaryClaudeDanger: "跳過權限提示，適合受控環境",
            .cmdSummaryCompact: "壓縮上下文，保留當前任務重點",
            .cmdSummaryInit: "產生或更新專案說明檔案",
            .cmdSummaryClear: "清除目前對話上下文",
            .cmdSummaryMemory: "檢視或管理 Claude 記憶",
            .cmdSummaryModel: "切換目前使用的模型",
            .cmdSummaryHelp: "檢視 Claude Code 說明",
            .cmdSummaryReview: "請求程式碼審查建議",
            .cmdSummaryStatus: "檢視目前對話與工具狀態",
            .cmdSummaryDiff: "檢視本次修改差異",
            .cmdSummaryCost: "檢視目前對話消耗",
            .cmdSummaryLogin: "登入或切換帳號",
            .cmdSummaryConfig: "開啟設定相關選項",
            .cmdSummaryMcp: "管理 MCP 伺服器連線",
            .cmdSummaryDoctor: "檢查本機環境問題",
            .cmdSummaryTerminalSetup: "設定終端機整合能力",
            .commandMoveUp: "上移",
            .commandMoveDown: "下移",
            .addCommandNameLabel: "名稱",
            .addCommandNamePlaceholder: "例如：開啟專案",
            .addCommandContentLabel: "輸入內容",
            .addCommandCancel: "取消",
            .addCommandConfirm: "確認",
            .personalityPetName: "寵物名稱",
            .personalityPetNamePlaceholder: "小寵",
            .personalityOwnerName: "主人名字",
            .personalityOwnerNamePlaceholder: "主人",
            .personalityPresetSection: "性格預設",
            .personalityCustomPrompt: "自訂 Prompt",
            .personalityPromptEditable: "Prompt（可繼續編輯）",
            .personalityConstraints: "約束條件",
            .personalityConstraintPlaceholder: "例如：只說中文、不說髒話...",
            .personalitySaveButton: "儲存設定",
            .personalitySaved: "已儲存",
            .personalitySaveFailed: "儲存失敗",
            .skinPickerTitle: "選擇外觀",
            .skinGlassDesc: "毛玻璃、柔和邊緣",
            .skinDarkDesc: "低亮度夜間面板",
            .skinPixelDesc: "硬邊框、像素感",
            .chatInputPlaceholder: "說點什麼…",
            .petImportedSection: "已匯入寵物",
            .petButtonChoose: "選擇",
            .petButtonChosen: "已選擇",
            .petTooltipDelete: "刪除寵物",
            .petTooltipKeepOne: "至少需要保留一個寵物",
            .tooltipChooseFolderAndCd: "選擇資料夾並輸入 cd",
            .tooltipChatWithPet: "與寵物聊天",
            .tooltipSwitchSkin: "切換外觀",
            .tooltipStopPomodoro: "停止番茄鐘",
            .tooltipStartBreak5: "開始休息 (5 分鐘)",
            .tooltipCloseStatus: "關閉狀態",
            .pomodoroStart25: "開始番茄鐘 (25 分鐘)",
            .pomodoroPausedRemain: "已暫停 · 剩餘 %@ · 點擊繼續",
            .pomodoroWorkingRemain: "工作中 · 剩餘 %@ · 點擊暫停",
            .pomodoroBreakPausedRemain: "休息已暫停 · 剩餘 %@ · 點擊繼續",
            .pomodoroBreakingRemain: "休息中 · 剩餘 %@ · 點擊暫停",
            .statusCommandsTab: "命令",
            .statusAllowHint: "允許 · %@",
            .statusDenyAuth: "拒絕授權",
            .petBuiltinTermicatName: "termicat",
            .petBuiltinTermicatDesc: "一隻蜷在迷你終端旁的彩虹像素小貓。",
            .petBuiltinJituiName: "雞腿",
            .petBuiltinJituiDesc: "開發者主人的貓咪。",
            .petBuiltinWizardClaudeName: "巫師克勞德",
            .petBuiltinWizardClaudeDesc: "戴著深藍魔法帽與披風的橙色巫師寵物，閃著小小的金色魔法。",
            .petBuiltinPixelJituiName: "像素雞腿",
            .petBuiltinPixelJituiDesc: "開發者的貓咪。",
            .petFromPetdexCommunity: "來自 Petdex 社群",
        ],
        .english: [
            .menuShowPet: "Show Pet",
            .menuSettings: "Settings...",
            .menuRequestAccessibility: "Request Accessibility Access",
            .menuOpenAccessibility: "Open Accessibility Settings",
            .menuInstallHook: "Install Claude Code Hook",
            .menuUninstallHook: "Uninstall Claude Code Hook",
            .menuQuit: "Quit",
            .settingsWindowTitle: "TermiPet Settings",
            .settingsAbout: "About",
            .settingsAppearance: "Appearance",
            .settingsLanguage: "Language",
            .settingsCommands: "Commands",
            .settingsPet: "Pet",
            .settingsPersonality: "Personality",
            .settingsModel: "Model",
            .languageTitle: "Choose interface language",
            .languageRestartNote: "Language changes take effect after restarting the app.",
            .saveConfig: "Save",
            .saved: "Saved",
            .petUnselected: "No pet selected",
            .petSelectPrompt: "Choose a pet folder that contains pet.json and spritesheet.",
            .petCurrentFolder: "Current folder",
            .petNoFolder: "None",
            .petChooseFolder: "Choose pet folder",
            .petImportFolder: "Import pet folder",
            .commandPanelTitle: "Commands",
            .commandPanelAdd: "Add custom command",
            .commandPanelPin: "Pin command panel",
            .commandPanelUnpin: "Unpin command panel",
            .quotaTitle: "AI Usage",
            .quotaRefresh: "Refresh usage",
            .quotaReading: "Reading",
            .quotaPending: "Pending",
            .quotaNoData: "No data",
            .quotaSynced: "Synced",
            .quotaLoginRequired: "Sign in",
            .quotaNotLoggedIn: "No login",
            .quotaError: "Error",
            .quotaReadingDetail: "Reading plan usage...",
            .quotaHoverDetail: "Hover to read plan usage",
            .quotaEmptyDetail: "No usage data to show",
            .quotaReset: "Reset",
            .actionIdle: "Idle",
            .actionRun: "Run",
            .actionMove: "Move",
            .actionHappy: "Happy",
            .actionAlert: "Alert",
            .actionError: "Error",
            .actionSleep: "Sleep",
            .actionThink: "Think",
            .actionCelebrate: "Celebrate",
            .contextMenuRandomPet: "Random Pet",
            .contextMenuSettings: "Settings...",
            .contextMenuQuit: "Quit Pet",
            .aboutVersion: "Version",
            .aboutTitle: "Desktop Floating Terminal Pet Assistant",
            .aboutDescription: "TermiPet is an intelligent desktop pet assistant that provides comprehensive programming support for developers.\n\nCore Features:\n• Quick Command Panel - Execute common terminal commands with one click\n• Real-time Terminal Preview - Auto-detect and display terminal output status\n• Claude Code Integration - Monitor AI coding assistant work status in real-time\n• Pomodoro Timer - Stay focused and maintain efficient work rhythm\n• AI Chat Conversation - Interact with your pet and get programming advice\n• Multiple Skin Themes - Switch between Glass, Dark, and Pixel styles\n• Custom Pets - Import personalized pet resource packs\n• Multi-language Support - Simplified Chinese, Traditional Chinese, English, Japanese, Korean\n• AI Usage Monitor - Real-time display of Claude/Copilot/ChatGPT quotas\n\nMake coding more efficient and fun!",
            .aboutDeveloper: "Developer",
            .aboutDeveloperName: "Developed by bleetchen",
            .aboutSocialMedia: "Social Media",
            .skinGlass: "Glass",
            .skinDark: "Dark",
            .skinPixel: "Pixel",
            .personalityHappy: "Happy",
            .personalityCodingPartner: "Coding Partner",
            .personalityGentleCoach: "Gentle Coach",
            .personalityFocused: "Focused",
            .personalityAngry: "Angry",
            .personalityLazy: "Lazy",
            .personalityEnergetic: "Energetic",
            .personalityWise: "Wise",
            .personalitySarcastic: "Sarcastic",
            .personalityCustom: "Custom",
            .menuEdit: "Edit",
            .menuClose: "Close Window",
            .menuUndo: "Undo",
            .menuRedo: "Redo",
            .menuCut: "Cut",
            .menuCopy: "Copy",
            .menuPaste: "Paste",
            .menuSelectAll: "Select All",
            .alertOK: "OK",
            .hookInstalledTitle: "Installed",
            .hookInstalledMessage: "Claude Code Hook was written. Restart any running claude processes to activate it.",
            .hookInstallFailedTitle: "Install Failed",
            .hookUninstalledTitle: "Uninstalled",
            .hookUninstalledMessage: "Claude Code Hook was removed from ~/.claude/settings.json.",
            .hookUninstallFailedTitle: "Uninstall Failed",
            .petFolderPanelPrompt: "Import",
            .petFolderPanelMessage: "Choose a pet folder that contains pet.json and the spritesheet.",
            .menuResetAccessibility: "Reset Accessibility Permission",
            .accessibilityResetTitle: "Accessibility Permission Reset",
            .accessibilityResetMessage: "The old TCC entries for TermiPet have been cleared. Please quit TermiPet and reopen it; the next time you tap a quick command you will see one fresh authorization prompt — choose Allow.",
            .accessibilityResetFailedTitle: "Reset Failed",
            .accessibilityNeedsAuthTitle: "Accessibility Permission Required",
            .accessibilityNeedsAuthMessage: "The text was copied to the clipboard. Switch to your terminal and press Cmd+V to paste.\n\nIf TermiPet appears enabled in System Settings but still prompts, you likely have multiple TermiPet.app copies on disk with different code-signing hashes. Please:\n1. Quit TermiPet\n2. System Settings → Privacy & Security → Accessibility, find TermiPet and click − to remove it\n3. Delete extra TermiPet.app copies and keep only the current build\n4. Reopen TermiPet, tap a quick command and approve the authorization\n\nYou can also use the menu bar's “Reset Accessibility Permission” to clean things up automatically.",
            .modelPetChatTitle: "Pet Chat Model",
            .modelRefresh: "Refresh",
            .modelProviderSource: "Model Source",
            .modelRedetect: "Re-detect",
            .modelSwitchToOnline: "Switch to Online API",
            .modelTagLocal: "Local Model",
            .modelTagDownloaded: "Downloaded",
            .modelButtonDownload: "Download",
            .modelButtonRetry: "Retry",
            .modelButtonDelete: "Delete Model",
            .modelDeleteConfirmTitle: "Delete %@?",
            .modelDeleteConfirmMessage: "This removes %@ from Ollama. You can download it again afterward to repair a damaged model or chat failure.",
            .modelStartOllama: "Start Ollama",
            .modelInstallOllama: "Install Ollama",
            .modelStarting: "Starting",
            .modelDownloadRecommended: "Download Recommended Model",
            .modelDownloadingShort: "Downloading",
            .modelUseLocal: "Use Local Model",
            .modelRetryDownload: "Retry Download",
            .modelOpenInstallPage: "Open Install Page",
            .modelSetupTitleNotInstalled: "Start the local model service first",
            .modelSetupTitleStarting: "Starting Ollama",
            .modelSetupTitleRunningNoModel: "Download recommended model",
            .modelSetupTitleDownloadingModel: "Model is downloading",
            .modelSetupTitleReady: "Local model is ready",
            .modelSetupTitleError: "Local model is not ready yet",
            .modelSetupMsgNotInstalled: "TermiPet did not detect Ollama. Try starting it first, or open the official install page if it is not installed.",
            .modelSetupMsgStarting: "Opening Ollama. Re-detection will happen automatically in a few seconds.",
            .modelSetupMsgRunningNoModelPrefix: "Ollama is running. Download ",
            .modelSetupMsgRunningNoModelSuffix: " so your pet can chat using a local model.",
            .modelSetupMsgDownloadingModel: "Keep your network connected. You can retry if the download is interrupted — existing settings won't be affected.",
            .modelSetupMsgReady: "A local model is available. TermiPet will prefer the selected local model.",
            .modelSetupMsgErrorFallback: "Make sure Ollama is running, or reopen the official install page.",
            .modelBadgeNotDetected: "Not Detected",
            .modelBadgeStarting: "Starting",
            .modelBadgePending: "Pending",
            .modelBadgeDownloading: "Downloading",
            .modelBadgeReady: "Ready",
            .modelBadgeError: "Action Needed",
            .modelOnlineApiProvider: "API Provider",
            .modelReadingShort: "Loading...",
            .modelReadModels: "Load Models",
            .modelTestingShort: "Testing...",
            .modelTestConnection: "Test Connection",
            .modelLabel: "Model",
            .modelSelectAfterRead: "Click \u{201C}Load Models\u{201D} to choose",
            .modelStateReadingList: "Loading model list",
            .modelStateReadDonePrefix: "Loaded ",
            .modelStateSendingTest: "Sending test message",
            .modelDownloadingProgressPrefix: "Downloading ",
            .modelSaveButton: "Save",
            .modelProviderLocal: "Local Model",
            .modelProviderOnline: "Online API",
            .modelOnlineProviderCustom: "Custom API",
            .ollamaDescQwenSmall: "Ultra lightweight, fits low-spec machines, great at Chinese",
            .ollamaDescQwenRecommended: "Recommended — best Chinese support and fast",
            .ollamaDescPhi35: "From Microsoft — compact yet high quality",
            .ollamaDescGemma1b: "From Google — balanced and lightweight",
            .commandsAdd: "Add",
            .commandsPinnedSection: "Pinned Commands",
            .commandsAllSection: "All Commands",
            .commandsDragSort: "Drag to reorder",
            .commandsUnpin: "Unpin",
            .commandsPin: "Pin",
            .commandsDelete: "Delete",
            .commandsAutoSave: "Auto-saved",
            .addCommandTitle: "Add Quick Command",
            .addCommandDescriptionLabel: "Description / Note",
            .addCommandDescriptionPlaceholder: "Explain what this command does",
            .cmdSummaryClaude: "Start an interactive Claude Code session",
            .cmdSummaryClaudeAuto: "Enable auto mode and reduce manual confirmations",
            .cmdSummaryClaudeDanger: "Skip permission prompts — for controlled environments",
            .cmdSummaryCompact: "Compact context and keep the current task focus",
            .cmdSummaryInit: "Generate or update the project description file",
            .cmdSummaryClear: "Clear the current conversation context",
            .cmdSummaryMemory: "View or manage Claude's memory",
            .cmdSummaryModel: "Switch the model currently in use",
            .cmdSummaryHelp: "View Claude Code help",
            .cmdSummaryReview: "Request code review suggestions",
            .cmdSummaryStatus: "View the current session and tool status",
            .cmdSummaryDiff: "View the current change diff",
            .cmdSummaryCost: "View the current session cost",
            .cmdSummaryLogin: "Sign in or switch accounts",
            .cmdSummaryConfig: "Open configuration options",
            .cmdSummaryMcp: "Manage MCP server connections",
            .cmdSummaryDoctor: "Diagnose local environment issues",
            .cmdSummaryTerminalSetup: "Configure terminal integration",
            .commandMoveUp: "Move Up",
            .commandMoveDown: "Move Down",
            .addCommandNameLabel: "Name",
            .addCommandNamePlaceholder: "e.g. Open Project",
            .addCommandContentLabel: "Command",
            .addCommandCancel: "Cancel",
            .addCommandConfirm: "Confirm",
            .personalityPetName: "Pet Name",
            .personalityPetNamePlaceholder: "Buddy",
            .personalityOwnerName: "Owner Name",
            .personalityOwnerNamePlaceholder: "Owner",
            .personalityPresetSection: "Personality Presets",
            .personalityCustomPrompt: "Custom Prompt",
            .personalityPromptEditable: "Prompt (editable)",
            .personalityConstraints: "Constraints",
            .personalityConstraintPlaceholder: "e.g. English only, no profanity...",
            .personalitySaveButton: "Save",
            .personalitySaved: "Saved",
            .personalitySaveFailed: "Save failed",
            .skinPickerTitle: "Choose Skin",
            .skinGlassDesc: "Frosted glass with soft edges",
            .skinDarkDesc: "Low-luminance night panel",
            .skinPixelDesc: "Hard border, pixel feel",
            .chatInputPlaceholder: "Say something…",
            .petImportedSection: "Imported Pets",
            .petButtonChoose: "Choose",
            .petButtonChosen: "Selected",
            .petTooltipDelete: "Delete pet",
            .petTooltipKeepOne: "At least one pet is required",
            .tooltipChooseFolderAndCd: "Choose folder and type cd",
            .tooltipChatWithPet: "Chat with pet",
            .tooltipSwitchSkin: "Switch skin",
            .tooltipStopPomodoro: "Stop Pomodoro",
            .tooltipStartBreak5: "Start break (5 min)",
            .tooltipCloseStatus: "Close status",
            .pomodoroStart25: "Start Pomodoro (25 min)",
            .pomodoroPausedRemain: "Paused · %@ left · Click to resume",
            .pomodoroWorkingRemain: "Working · %@ left · Click to pause",
            .pomodoroBreakPausedRemain: "Break paused · %@ left · Click to resume",
            .pomodoroBreakingRemain: "On break · %@ left · Click to pause",
            .statusCommandsTab: "Commands",
            .statusAllowHint: "Allow · %@",
            .statusDenyAuth: "Deny",
            .petBuiltinTermicatName: "termicat",
            .petBuiltinTermicatDesc: "A compact rainbow pixel cat curled beside a tiny terminal.",
            .petBuiltinJituiName: "Jitui",
            .petBuiltinJituiDesc: "The developer's owner's cat.",
            .petBuiltinWizardClaudeName: "Wizard Kelaude",
            .petBuiltinWizardClaudeDesc: "An orange wizard pet with a navy hat and cloak, sparkling with tiny golden magic.",
            .petBuiltinPixelJituiName: "Pixel Jitui",
            .petBuiltinPixelJituiDesc: "The developer's cat.",
            .petFromPetdexCommunity: "From the Petdex community",
        ],
        .japanese: [
            .menuShowPet: "ペットを表示",
            .menuSettings: "設定...",
            .menuRequestAccessibility: "アクセシビリティ権限を要求",
            .menuOpenAccessibility: "アクセシビリティ設定を開く",
            .menuInstallHook: "Claude Code Hook をインストール",
            .menuUninstallHook: "Claude Code Hook をアンインストール",
            .menuQuit: "終了",
            .settingsWindowTitle: "TermiPet 設定",
            .settingsAbout: "情報",
            .settingsAppearance: "外観",
            .settingsLanguage: "言語",
            .settingsCommands: "コマンド",
            .settingsPet: "ペット",
            .settingsPersonality: "性格",
            .settingsModel: "モデル",
            .languageTitle: "表示言語を選択",
            .languageRestartNote: "言語の変更はアプリの再起動後に反映されます。",
            .saveConfig: "保存",
            .saved: "保存済み",
            .petUnselected: "ペット未選択",
            .petSelectPrompt: "pet.json と spritesheet を含むペットフォルダを選択してください。",
            .petCurrentFolder: "現在のフォルダ",
            .petNoFolder: "なし",
            .petChooseFolder: "ペットフォルダを選択",
            .petImportFolder: "ペットフォルダを読み込む",
            .commandPanelTitle: "コマンド",
            .commandPanelAdd: "カスタムコマンドを追加",
            .commandPanelPin: "コマンドパネルを固定",
            .commandPanelUnpin: "コマンドパネルの固定を解除",
            .quotaTitle: "AI 使用量",
            .quotaRefresh: "使用量を更新",
            .quotaReading: "読込中",
            .quotaPending: "未読込",
            .quotaNoData: "データなし",
            .quotaSynced: "同期済み",
            .quotaLoginRequired: "ログイン必要",
            .quotaNotLoggedIn: "未ログイン",
            .quotaError: "エラー",
            .quotaReadingDetail: "プラン使用量を読込中...",
            .quotaHoverDetail: "ホバーして使用量を読込",
            .quotaEmptyDetail: "表示できる使用量データがありません",
            .quotaReset: "リセット済み",
            .actionIdle: "待機",
            .actionRun: "実行",
            .actionMove: "移動",
            .actionHappy: "喜び",
            .actionAlert: "通知",
            .actionError: "エラー",
            .actionSleep: "睡眠",
            .actionThink: "思考",
            .actionCelebrate: "祝う",
            .contextMenuRandomPet: "ランダムペット",
            .contextMenuSettings: "設定...",
            .contextMenuQuit: "ペットを閉じる",
            .aboutVersion: "バージョン",
            .aboutTitle: "デスクトップフローティングターミナルペットアシスタント",
            .aboutDescription: "TermiPet は、開発者に包括的なプログラミング支援を提供するインテリジェントなデスクトップペットアシスタントです。\n\nコア機能：\n• クイックコマンドパネル - よく使うターミナルコマンドをワンクリックで実行\n• リアルタイムターミナルプレビュー - ターミナル出力状態を自動検出して表示\n• Claude Code 統合 - AI コーディングアシスタントの作業状態をリアルタイムで監視\n• ポモドーロタイマー - 集中力を維持し、効率的な作業リズムを保つ\n• AI チャット会話 - ペットと対話してプログラミングのアドバイスを得る\n• 複数のスキンテーマ - ガラス、ダーク、ピクセルスタイルを切り替え\n• カスタムペット - パーソナライズされたペットリソースパックをインポート\n• 多言語サポート - 簡体字中国語、繁体字中国語、英語、日本語、韓国語\n• AI 使用量モニター - Claude/Copilot/ChatGPT のクォータをリアルタイム表示\n\nコーディングをより効率的で楽しく！",
            .aboutDeveloper: "開発者",
            .aboutDeveloperName: "bleetchen により開発",
            .aboutSocialMedia: "ソーシャルメディア",
            .skinGlass: "ガラス",
            .skinDark: "ダーク",
            .skinPixel: "ピクセル",
            .personalityHappy: "ハッピー",
            .personalityCodingPartner: "コーディングパートナー",
            .personalityGentleCoach: "優しいコーチ",
            .personalityFocused: "集中",
            .personalityAngry: "怒り",
            .personalityLazy: "怠惰",
            .personalityEnergetic: "エネルギッシュ",
            .personalityWise: "賢明",
            .personalitySarcastic: "皮肉",
            .personalityCustom: "カスタム",
            .menuEdit: "編集",
            .menuClose: "ウィンドウを閉じる",
            .menuUndo: "取り消し",
            .menuRedo: "やり直し",
            .menuCut: "カット",
            .menuCopy: "コピー",
            .menuPaste: "ペースト",
            .menuSelectAll: "すべてを選択",
            .alertOK: "OK",
            .hookInstalledTitle: "インストール済み",
            .hookInstalledMessage: "Claude Code Hook を書き込みました。実行中の claude プロセスを再起動して反映してください。",
            .hookInstallFailedTitle: "インストール失敗",
            .hookUninstalledTitle: "アンインストール済み",
            .hookUninstalledMessage: "Claude Code Hook を ~/.claude/settings.json から削除しました。",
            .hookUninstallFailedTitle: "アンインストール失敗",
            .petFolderPanelPrompt: "読み込む",
            .petFolderPanelMessage: "pet.json と spritesheet を含むペットフォルダを選択してください。",
            .menuResetAccessibility: "アクセシビリティ権限をリセット",
            .accessibilityResetTitle: "アクセシビリティ権限をリセットしました",
            .accessibilityResetMessage: "TermiPet に関する古い TCC レコードを削除しました。TermiPet を終了して再度開いてください。次にクイックコマンドを押したときに新しい承認ダイアログが表示されるので「許可」を選択してください。",
            .accessibilityResetFailedTitle: "リセット失敗",
            .accessibilityNeedsAuthTitle: "アクセシビリティ権限が必要",
            .accessibilityNeedsAuthMessage: "内容はクリップボードにコピーされました。ターミナルに切り替えて Cmd+V で貼り付けてください。\n\nシステム設定で TermiPet にチェックが入っているのに警告が出る場合は、ディスク上に異なる署名ハッシュを持つ複数の TermiPet.app が存在する可能性があります。次の手順で対処してください:\n1. TermiPet を終了\n2. システム設定 → プライバシーとセキュリティ → アクセシビリティ で TermiPet を選び − ボタンで削除\n3. 余分な TermiPet.app をすべて削除し、現在のビルドだけ残す\n4. TermiPet を再起動し、クイックコマンドを押して権限を承認\n\nメニューバーの「アクセシビリティ権限をリセット」からワンクリックでクリーンアップすることもできます。",
            .modelPetChatTitle: "ペット対話モデル",
            .modelRefresh: "更新",
            .modelProviderSource: "モデルソース",
            .modelRedetect: "再検出",
            .modelSwitchToOnline: "オンライン API に切替",
            .modelTagLocal: "ローカルモデル",
            .modelTagDownloaded: "ダウンロード済み",
            .modelButtonDownload: "ダウンロード",
            .modelButtonRetry: "再試行",
            .modelButtonDelete: "モデルを削除",
            .modelDeleteConfirmTitle: "%@ を削除しますか？",
            .modelDeleteConfirmMessage: "%@ を Ollama から削除します。削除後に再ダウンロードすると、破損したモデルやチャット失敗を修復できます。",
            .modelStartOllama: "Ollama を起動",
            .modelInstallOllama: "Ollama をインストール",
            .modelStarting: "起動中",
            .modelDownloadRecommended: "推奨モデルをダウンロード",
            .modelDownloadingShort: "ダウンロード中",
            .modelUseLocal: "ローカルモデルを使用",
            .modelRetryDownload: "ダウンロードを再試行",
            .modelOpenInstallPage: "インストールページを開く",
            .modelSetupTitleNotInstalled: "まずローカルモデルサービスを起動",
            .modelSetupTitleStarting: "Ollama を起動中",
            .modelSetupTitleRunningNoModel: "推奨モデルをダウンロード",
            .modelSetupTitleDownloadingModel: "モデルをダウンロード中",
            .modelSetupTitleReady: "ローカルモデルは準備完了",
            .modelSetupTitleError: "ローカルモデルがまだ準備できていません",
            .modelSetupMsgNotInstalled: "TermiPet は Ollama を検出できませんでした。まず起動を試し、未インストールの場合は公式インストールページを開いてください。",
            .modelSetupMsgStarting: "Ollama を開いています。数秒後に自動的に再検出されます。",
            .modelSetupMsgRunningNoModelPrefix: "Ollama は実行中です。",
            .modelSetupMsgRunningNoModelSuffix: " をダウンロードすると、ペットはローカルモデルでチャットできます。",
            .modelSetupMsgDownloadingModel: "ネットワーク接続を維持してください。中断後も再試行可能で、既存の設定には影響しません。",
            .modelSetupMsgReady: "使用可能なローカルモデルがあります。TermiPet は選択中のローカルモデルを優先して使用します。",
            .modelSetupMsgErrorFallback: "Ollama が実行中か確認するか、公式インストールページを再度開いてください。",
            .modelBadgeNotDetected: "未検出",
            .modelBadgeStarting: "起動中",
            .modelBadgePending: "未取得",
            .modelBadgeDownloading: "ダウンロード中",
            .modelBadgeReady: "準備完了",
            .modelBadgeError: "対応必要",
            .modelOnlineApiProvider: "API プロバイダ",
            .modelReadingShort: "読込中...",
            .modelReadModels: "モデルを読込",
            .modelTestingShort: "テスト中...",
            .modelTestConnection: "接続をテスト",
            .modelLabel: "モデル",
            .modelSelectAfterRead: "\u{300C}モデルを読込\u{300D}をクリックして選択",
            .modelStateReadingList: "モデルリストを読込中",
            .modelStateReadDonePrefix: "読込済み ",
            .modelStateSendingTest: "テストメッセージを送信中",
            .modelDownloadingProgressPrefix: "ダウンロード中 ",
            .modelSaveButton: "保存",
            .modelProviderLocal: "ローカルモデル",
            .modelProviderOnline: "オンライン API",
            .modelOnlineProviderCustom: "カスタム API",
            .ollamaDescQwenSmall: "超軽量、低スペックに最適、中国語が得意",
            .ollamaDescQwenRecommended: "推奨、中国語サポート最良で高速",
            .ollamaDescPhi35: "Microsoft 製、小型ながら高品質",
            .ollamaDescGemma1b: "Google 製、バランスの取れた軽量モデル",
            .commandsAdd: "追加",
            .commandsPinnedSection: "ピン留めコマンド",
            .commandsAllSection: "すべてのコマンド",
            .commandsDragSort: "ドラッグで並び替え",
            .commandsUnpin: "ピン解除",
            .commandsPin: "ピン留め",
            .commandsDelete: "削除",
            .commandsAutoSave: "自動保存",
            .addCommandTitle: "クイックコマンドを追加",
            .addCommandDescriptionLabel: "説明 / メモ",
            .addCommandDescriptionPlaceholder: "このコマンドの目的を説明",
            .cmdSummaryClaude: "Claude Code の対話セッションを開始",
            .cmdSummaryClaudeAuto: "自動モードを有効にして手動確認を減らす",
            .cmdSummaryClaudeDanger: "権限プロンプトをスキップ、制御された環境向け",
            .cmdSummaryCompact: "コンテキストを圧縮し、現在のタスクの要点を保持",
            .cmdSummaryInit: "プロジェクト説明ファイルを生成または更新",
            .cmdSummaryClear: "現在の対話コンテキストをクリア",
            .cmdSummaryMemory: "Claude のメモリを表示・管理",
            .cmdSummaryModel: "現在使用中のモデルを切替",
            .cmdSummaryHelp: "Claude Code ヘルプを表示",
            .cmdSummaryReview: "コードレビュー提案を依頼",
            .cmdSummaryStatus: "現在のセッションとツールの状態を表示",
            .cmdSummaryDiff: "今回の変更差分を表示",
            .cmdSummaryCost: "現在のセッションの消費を表示",
            .cmdSummaryLogin: "ログインまたはアカウント切替",
            .cmdSummaryConfig: "設定オプションを開く",
            .cmdSummaryMcp: "MCP サーバー接続を管理",
            .cmdSummaryDoctor: "ローカル環境の問題を診断",
            .cmdSummaryTerminalSetup: "ターミナル統合機能を設定",
            .commandMoveUp: "上へ移動",
            .commandMoveDown: "下へ移動",
            .addCommandNameLabel: "名前",
            .addCommandNamePlaceholder: "例：プロジェクトを開く",
            .addCommandContentLabel: "コマンド",
            .addCommandCancel: "キャンセル",
            .addCommandConfirm: "確認",
            .personalityPetName: "ペット名",
            .personalityPetNamePlaceholder: "ペット",
            .personalityOwnerName: "飼い主の名前",
            .personalityOwnerNamePlaceholder: "飼い主",
            .personalityPresetSection: "性格プリセット",
            .personalityCustomPrompt: "カスタムプロンプト",
            .personalityPromptEditable: "プロンプト（編集可）",
            .personalityConstraints: "制約条件",
            .personalityConstraintPlaceholder: "例：日本語のみ、汚い言葉禁止...",
            .personalitySaveButton: "保存",
            .personalitySaved: "保存済み",
            .personalitySaveFailed: "保存に失敗",
            .skinPickerTitle: "スキンを選択",
            .skinGlassDesc: "すりガラス、柔らかいエッジ",
            .skinDarkDesc: "低輝度ナイトパネル",
            .skinPixelDesc: "硬いボーダー、ピクセル感",
            .chatInputPlaceholder: "何か話す…",
            .petImportedSection: "インポート済みペット",
            .petButtonChoose: "選択",
            .petButtonChosen: "選択済み",
            .petTooltipDelete: "ペットを削除",
            .petTooltipKeepOne: "少なくとも 1 匹のペットが必要",
            .tooltipChooseFolderAndCd: "フォルダを選択して cd を入力",
            .tooltipChatWithPet: "ペットとチャット",
            .tooltipSwitchSkin: "スキンを切替",
            .tooltipStopPomodoro: "ポモドーロを停止",
            .tooltipStartBreak5: "休憩開始 (5 分)",
            .tooltipCloseStatus: "ステータスを閉じる",
            .pomodoroStart25: "ポモドーロ開始 (25 分)",
            .pomodoroPausedRemain: "一時停止 · 残り %@ · クリックで再開",
            .pomodoroWorkingRemain: "作業中 · 残り %@ · クリックで一時停止",
            .pomodoroBreakPausedRemain: "休憩一時停止 · 残り %@ · クリックで再開",
            .pomodoroBreakingRemain: "休憩中 · 残り %@ · クリックで一時停止",
            .statusCommandsTab: "コマンド",
            .statusAllowHint: "許可 · %@",
            .statusDenyAuth: "拒否",
            .petBuiltinTermicatName: "termicat",
            .petBuiltinTermicatDesc: "小さなターミナルに寄り添うレインボーピクセル猫。",
            .petBuiltinJituiName: "チキンレッグ",
            .petBuiltinJituiDesc: "開発者の飼い主の猫。",
            .petBuiltinWizardClaudeName: "ウィザード・ケロード",
            .petBuiltinWizardClaudeDesc: "ネイビーの帽子とマントを纏ったオレンジ色のウィザードペット。小さな金色の魔法が輝く。",
            .petBuiltinPixelJituiName: "ピクセルチキンレッグ",
            .petBuiltinPixelJituiDesc: "開発者の猫。",
            .petFromPetdexCommunity: "Petdex コミュニティより",
        ],
        .korean: [
            .menuShowPet: "펫 보이기",
            .menuSettings: "설정...",
            .menuRequestAccessibility: "손쉬운 사용 권한 요청",
            .menuOpenAccessibility: "손쉬운 사용 설정 열기",
            .menuInstallHook: "Claude Code Hook 설치",
            .menuUninstallHook: "Claude Code Hook 제거",
            .menuQuit: "종료",
            .settingsWindowTitle: "TermiPet 설정",
            .settingsAbout: "정보",
            .settingsAppearance: "외관",
            .settingsLanguage: "언어",
            .settingsCommands: "명령",
            .settingsPet: "펫",
            .settingsPersonality: "성격",
            .settingsModel: "모델",
            .languageTitle: "인터페이스 언어 선택",
            .languageRestartNote: "언어 변경은 앱을 다시 시작한 뒤 적용됩니다.",
            .saveConfig: "저장",
            .saved: "저장됨",
            .petUnselected: "선택된 펫 없음",
            .petSelectPrompt: "pet.json 과 spritesheet 가 들어 있는 펫 폴더를 선택하세요.",
            .petCurrentFolder: "현재 폴더",
            .petNoFolder: "없음",
            .petChooseFolder: "펫 폴더 선택",
            .petImportFolder: "펫 폴더 가져오기",
            .commandPanelTitle: "명령",
            .commandPanelAdd: "사용자 명령 추가",
            .commandPanelPin: "명령 패널 고정",
            .commandPanelUnpin: "명령 패널 고정 해제",
            .quotaTitle: "AI 사용량",
            .quotaRefresh: "사용량 새로고침",
            .quotaReading: "읽는 중",
            .quotaPending: "대기 중",
            .quotaNoData: "데이터 없음",
            .quotaSynced: "동기화됨",
            .quotaLoginRequired: "로그인 필요",
            .quotaNotLoggedIn: "미로그인",
            .quotaError: "오류",
            .quotaReadingDetail: "요금제 사용량을 읽는 중...",
            .quotaHoverDetail: "호버하면 사용량을 읽습니다",
            .quotaEmptyDetail: "표시할 사용량 데이터가 없습니다",
            .quotaReset: "재설정됨",
            .actionIdle: "대기",
            .actionRun: "실행",
            .actionMove: "이동",
            .actionHappy: "기쁨",
            .actionAlert: "알림",
            .actionError: "오류",
            .actionSleep: "수면",
            .actionThink: "생각",
            .actionCelebrate: "축하",
            .contextMenuRandomPet: "랜덤 펫",
            .contextMenuSettings: "설정...",
            .contextMenuQuit: "펫 닫기",
            .aboutVersion: "버전",
            .aboutTitle: "데스크톱 플로팅 터미널 펫 어시스턴트",
            .aboutDescription: "TermiPet은 개발자에게 포괄적인 프로그래밍 지원을 제공하는 지능형 데스크톱 펫 어시스턴트입니다.\n\n핵심 기능:\n• 빠른 명령 패널 - 자주 사용하는 터미널 명령을 한 번의 클릭으로 실행\n• 실시간 터미널 미리보기 - 터미널 출력 상태를 자동 감지하고 표시\n• Claude Code 통합 - AI 코딩 어시스턴트 작업 상태를 실시간으로 모니터링\n• 포모도로 타이머 - 집중력을 유지하고 효율적인 작업 리듬 유지\n• AI 채팅 대화 - 펫과 상호작용하고 프로그래밍 조언 받기\n• 다중 스킨 테마 - 글래스, 다크, 픽셀 스타일 전환\n• 커스텀 펫 - 개인화된 펫 리소스 팩 가져오기\n• 다국어 지원 - 간체 중국어, 번체 중국어, 영어, 일본어, 한국어\n• AI 사용량 모니터 - Claude/Copilot/ChatGPT 할당량 실시간 표시\n\n코딩을 더 효율적이고 재미있게!",
            .aboutDeveloper: "개발자",
            .aboutDeveloperName: "bleetchen이 개발",
            .aboutSocialMedia: "소셜 미디어",
            .skinGlass: "글래스",
            .skinDark: "다크",
            .skinPixel: "픽셀",
            .personalityHappy: "행복",
            .personalityCodingPartner: "코딩 파트너",
            .personalityGentleCoach: "부드러운 코치",
            .personalityFocused: "집중",
            .personalityAngry: "화남",
            .personalityLazy: "게으름",
            .personalityEnergetic: "활기찬",
            .personalityWise: "현명한",
            .personalitySarcastic: "냉소적",
            .personalityCustom: "커스텀",
            .menuEdit: "편집",
            .menuClose: "윈도우 닫기",
            .menuUndo: "실행 취소",
            .menuRedo: "다시 실행",
            .menuCut: "잘라내기",
            .menuCopy: "복사",
            .menuPaste: "붙여넣기",
            .menuSelectAll: "전체 선택",
            .alertOK: "확인",
            .hookInstalledTitle: "설치됨",
            .hookInstalledMessage: "Claude Code Hook이 작성되었습니다. 실행 중인 claude 프로세스를 다시 시작하여 적용하세요.",
            .hookInstallFailedTitle: "설치 실패",
            .hookUninstalledTitle: "제거됨",
            .hookUninstalledMessage: "Claude Code Hook을 ~/.claude/settings.json 에서 제거했습니다.",
            .hookUninstallFailedTitle: "제거 실패",
            .petFolderPanelPrompt: "가져오기",
            .petFolderPanelMessage: "pet.json 과 spritesheet 가 들어 있는 펫 폴더를 선택하세요.",
            .menuResetAccessibility: "손쉬운 사용 권한 재설정",
            .accessibilityResetTitle: "손쉬운 사용 권한이 재설정되었습니다",
            .accessibilityResetMessage: "TermiPet 의 이전 TCC 항목을 삭제했습니다. TermiPet 을 종료하고 다시 열어주세요. 다음에 단축 명령을 누르면 새로운 승인 대화상자가 나타납니다. \"허용\"을 선택하세요.",
            .accessibilityResetFailedTitle: "재설정 실패",
            .accessibilityNeedsAuthTitle: "손쉬운 사용 권한 필요",
            .accessibilityNeedsAuthMessage: "내용이 클립보드에 복사되었습니다. 터미널로 전환한 후 Cmd+V 로 붙여넣으세요.\n\n시스템 설정에서 TermiPet 이 활성화되어 있는데도 계속 요청한다면, 디스크에 코드 서명 해시가 다른 여러 개의 TermiPet.app 사본이 있을 수 있습니다. 다음을 시도하세요:\n1. TermiPet 종료\n2. 시스템 설정 → 개인정보 보호 및 보안 → 손쉬운 사용 에서 TermiPet 을 찾아 − 버튼으로 제거\n3. 여분의 TermiPet.app 사본을 모두 삭제하고 현재 빌드만 남김\n4. TermiPet 을 다시 열고 단축 명령을 눌러 권한을 승인\n\n메뉴 바의 \"손쉬운 사용 권한 재설정\" 으로 자동 정리할 수도 있습니다.",
            .modelPetChatTitle: "펫 채팅 모델",
            .modelRefresh: "새로고침",
            .modelProviderSource: "모델 소스",
            .modelRedetect: "다시 감지",
            .modelSwitchToOnline: "온라인 API 로 전환",
            .modelTagLocal: "로컬 모델",
            .modelTagDownloaded: "다운로드됨",
            .modelButtonDownload: "다운로드",
            .modelButtonRetry: "재시도",
            .modelButtonDelete: "모델 삭제",
            .modelDeleteConfirmTitle: "%@ 삭제?",
            .modelDeleteConfirmMessage: "%@ 모델을 Ollama 에서 삭제합니다. 삭제 후 다시 다운로드하면 손상된 모델이나 채팅 실패를 복구할 수 있습니다.",
            .modelStartOllama: "Ollama 시작",
            .modelInstallOllama: "Ollama 설치",
            .modelStarting: "시작 중",
            .modelDownloadRecommended: "추천 모델 다운로드",
            .modelDownloadingShort: "다운로드 중",
            .modelUseLocal: "로컬 모델 사용",
            .modelRetryDownload: "다운로드 재시도",
            .modelOpenInstallPage: "설치 페이지 열기",
            .modelSetupTitleNotInstalled: "먼저 로컬 모델 서비스를 시작하세요",
            .modelSetupTitleStarting: "Ollama 시작 중",
            .modelSetupTitleRunningNoModel: "추천 모델 다운로드",
            .modelSetupTitleDownloadingModel: "모델 다운로드 중",
            .modelSetupTitleReady: "로컬 모델 준비 완료",
            .modelSetupTitleError: "로컬 모델이 아직 준비되지 않았습니다",
            .modelSetupMsgNotInstalled: "TermiPet 이 Ollama 를 감지하지 못했습니다. 먼저 시작을 시도하고, 설치되지 않은 경우 공식 설치 페이지를 여세요.",
            .modelSetupMsgStarting: "Ollama 를 여는 중입니다. 몇 초 후 자동으로 다시 감지됩니다.",
            .modelSetupMsgRunningNoModelPrefix: "Ollama 가 실행 중입니다. ",
            .modelSetupMsgRunningNoModelSuffix: " 을(를) 다운로드하면 펫이 로컬 모델로 채팅할 수 있습니다.",
            .modelSetupMsgDownloadingModel: "네트워크 연결을 유지하세요. 다운로드가 중단되어도 재시도할 수 있으며 기존 설정에는 영향이 없습니다.",
            .modelSetupMsgReady: "사용 가능한 로컬 모델이 있습니다. TermiPet 은 선택된 로컬 모델을 우선 사용합니다.",
            .modelSetupMsgErrorFallback: "Ollama 가 실행 중인지 확인하거나 공식 설치 페이지를 다시 여세요.",
            .modelBadgeNotDetected: "감지 안 됨",
            .modelBadgeStarting: "시작 중",
            .modelBadgePending: "대기 중",
            .modelBadgeDownloading: "다운로드 중",
            .modelBadgeReady: "준비됨",
            .modelBadgeError: "조치 필요",
            .modelOnlineApiProvider: "API 제공자",
            .modelReadingShort: "읽는 중...",
            .modelReadModels: "모델 읽기",
            .modelTestingShort: "테스트 중...",
            .modelTestConnection: "연결 테스트",
            .modelLabel: "모델",
            .modelSelectAfterRead: "\u{201C}모델 읽기\u{201D}를 클릭하여 선택",
            .modelStateReadingList: "모델 목록을 읽는 중",
            .modelStateReadDonePrefix: "읽음 ",
            .modelStateSendingTest: "테스트 메시지 전송 중",
            .modelDownloadingProgressPrefix: "다운로드 중 ",
            .modelSaveButton: "저장",
            .modelProviderLocal: "로컬 모델",
            .modelProviderOnline: "온라인 API",
            .modelOnlineProviderCustom: "사용자 정의 API",
            .ollamaDescQwenSmall: "초경량, 저사양에 적합, 중국어 우수",
            .ollamaDescQwenRecommended: "추천, 중국어 지원 최고, 빠른 속도",
            .ollamaDescPhi35: "Microsoft 제, 소형이지만 고품질",
            .ollamaDescGemma1b: "Google 제, 균형 잡힌 경량 모델",
            .commandsAdd: "추가",
            .commandsPinnedSection: "고정된 명령",
            .commandsAllSection: "모든 명령",
            .commandsDragSort: "드래그하여 정렬",
            .commandsUnpin: "고정 해제",
            .commandsPin: "고정",
            .commandsDelete: "삭제",
            .commandsAutoSave: "자동 저장",
            .addCommandTitle: "빠른 명령 추가",
            .addCommandDescriptionLabel: "설명 / 메모",
            .addCommandDescriptionPlaceholder: "이 명령이 무엇을 하는지 설명",
            .cmdSummaryClaude: "Claude Code 대화 세션 시작",
            .cmdSummaryClaudeAuto: "자동 모드 활성화로 수동 확인 감소",
            .cmdSummaryClaudeDanger: "권한 프롬프트 건너뛰기, 제어된 환경용",
            .cmdSummaryCompact: "컨텍스트 압축, 현재 작업 초점 유지",
            .cmdSummaryInit: "프로젝트 설명 파일 생성 또는 업데이트",
            .cmdSummaryClear: "현재 대화 컨텍스트 지우기",
            .cmdSummaryMemory: "Claude 메모리 보기 또는 관리",
            .cmdSummaryModel: "현재 사용 모델 전환",
            .cmdSummaryHelp: "Claude Code 도움말 보기",
            .cmdSummaryReview: "코드 리뷰 제안 요청",
            .cmdSummaryStatus: "현재 세션 및 도구 상태 보기",
            .cmdSummaryDiff: "이번 수정 차이 보기",
            .cmdSummaryCost: "현재 세션 사용량 보기",
            .cmdSummaryLogin: "로그인 또는 계정 전환",
            .cmdSummaryConfig: "설정 옵션 열기",
            .cmdSummaryMcp: "MCP 서버 연결 관리",
            .cmdSummaryDoctor: "로컬 환경 문제 진단",
            .cmdSummaryTerminalSetup: "터미널 통합 기능 구성",
            .commandMoveUp: "위로 이동",
            .commandMoveDown: "아래로 이동",
            .addCommandNameLabel: "이름",
            .addCommandNamePlaceholder: "예: 프로젝트 열기",
            .addCommandContentLabel: "명령 내용",
            .addCommandCancel: "취소",
            .addCommandConfirm: "확인",
            .personalityPetName: "펫 이름",
            .personalityPetNamePlaceholder: "펫",
            .personalityOwnerName: "주인 이름",
            .personalityOwnerNamePlaceholder: "주인",
            .personalityPresetSection: "성격 프리셋",
            .personalityCustomPrompt: "사용자 정의 프롬프트",
            .personalityPromptEditable: "프롬프트 (편집 가능)",
            .personalityConstraints: "제약 조건",
            .personalityConstraintPlaceholder: "예: 한국어만, 욕설 금지...",
            .personalitySaveButton: "저장",
            .personalitySaved: "저장됨",
            .personalitySaveFailed: "저장 실패",
            .skinPickerTitle: "스킨 선택",
            .skinGlassDesc: "젖빛 유리, 부드러운 가장자리",
            .skinDarkDesc: "저휘도 야간 패널",
            .skinPixelDesc: "단단한 테두리, 픽셀 느낌",
            .chatInputPlaceholder: "무언가 말해보세요…",
            .petImportedSection: "가져온 펫",
            .petButtonChoose: "선택",
            .petButtonChosen: "선택됨",
            .petTooltipDelete: "펫 삭제",
            .petTooltipKeepOne: "최소 한 마리의 펫이 필요합니다",
            .tooltipChooseFolderAndCd: "폴더 선택 후 cd 입력",
            .tooltipChatWithPet: "펫과 채팅",
            .tooltipSwitchSkin: "스킨 전환",
            .tooltipStopPomodoro: "포모도로 중지",
            .tooltipStartBreak5: "휴식 시작 (5 분)",
            .tooltipCloseStatus: "상태 닫기",
            .pomodoroStart25: "포모도로 시작 (25 분)",
            .pomodoroPausedRemain: "일시정지 · 남은 시간 %@ · 클릭하여 재개",
            .pomodoroWorkingRemain: "작업 중 · 남은 시간 %@ · 클릭하여 일시정지",
            .pomodoroBreakPausedRemain: "휴식 일시정지 · 남은 시간 %@ · 클릭하여 재개",
            .pomodoroBreakingRemain: "휴식 중 · 남은 시간 %@ · 클릭하여 일시정지",
            .statusCommandsTab: "명령",
            .statusAllowHint: "허용 · %@",
            .statusDenyAuth: "거부",
            .petBuiltinTermicatName: "termicat",
            .petBuiltinTermicatDesc: "작은 터미널 옆에 웅크린 무지개 픽셀 고양이.",
            .petBuiltinJituiName: "치킨 다리",
            .petBuiltinJituiDesc: "개발자 주인의 고양이.",
            .petBuiltinWizardClaudeName: "마법사 클로드",
            .petBuiltinWizardClaudeDesc: "남색 모자와 망토를 두른 주황색 마법사 펫. 작은 금빛 마법이 반짝입니다.",
            .petBuiltinPixelJituiName: "픽셀 치킨다리",
            .petBuiltinPixelJituiDesc: "개발자의 고양이.",
            .petFromPetdexCommunity: "Petdex 커뮤니티에서",
        ],
    ]
}
